PROJECT_ROOT: ""
SRC_DIR: ""
EXPLICIT_KG_DIR: ""
OUTPUT_DIR: output
APIConfig:
  API_BASE: ""
  API_KEY: ""
  MODEL_NAME: gpt-4o-mini
  TIMEOUT_SECS: 120
include_files:
- extraction.yaml
- text.yaml
- summarize.yaml